# Generated by Django 2.2.1 on 2019-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='score',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='game',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(max_length=3),
        ),
    ]
